name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Install dependencies
      run: |
        go version

    - name: Build
      run: go build .

    - name: Test With Coverage
      run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Run Vet & Lint
      run: |
        go vet ./...
        go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0 run -v --timeout=600s


